apiVersion: apps/v1
kind: ReplicaSet
metadata:
 name: web-rs
spec:
 replicas: 1
 selector:
  matchLabels:
   app: hello-world
 template:
  metadata:
   labels:
    app: hello-world
  spec:
   securityContext:
    # the group id of the owner of the actual directory behind the volume
    # This is actually a leaking abstraction, but the only solution that I have.
    # A better way would've been to have an appropriate ownership on the mounted dir, I guess...?
    supplementalGroups: [1000] 
   containers:
   - name: hello-ctr
     image: nigelpoulton/k8sbook:latest
     ports:
     - containerPort: 8080
     volumeMounts:
     # name must match the volume name below
      - name: models
        mountPath: "/models"
   volumes:
   - name: models
     persistentVolumeClaim:
      claimName: models